//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by register.rc
//
#define IDC_DELETE                      2
#define IDC_UPDATE_SUBJECT              3
#define IDC_ADDSUBJECT                  3
#define IDC_CANCEL                      4
#define IDCANCEL2                       4
#define IDC_ADD_SUBJECT                 4
#define IDC_EXIT                        5
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_REGISTER_DIALOG             102
#define IDD_SUBJECT_DIALOG              103
#define IDD_CURRICULUM_DIALOG           104
#define IDD_INFORMATIONS                105
#define IDR_MAINFRAME                   128
#define IDD_MAIN_DIALOG                 130
#define IDD_STDINFORMATION_DIALOG       131
#define IDD_STDADD_DIALOG               132
#define IDD_STDSELECT_DIALOG            134
#define IDD_STDEDIT_DIALOG              135
#define IDD_REGISTERINFO_DIALOG         137
#define IDD_SELECTSTDID_DIALOG          140
#define IDD_ROOM_DIALOG                 141
#define IDD_SUBJECTINFO_DIALOG          143
#define IDD_SUBJECTADD_DIALOG           144
#define IDD_SUBJECT_SELECT_DIALOG       147
#define IDD_FACULTY_DIALOG              148
#define IDD_FACULTY_ADD_DIALOG          150
#define IDD_FACULTY_FUNCTION_DIALOG     151
#define IDD_DEPARTMENT_EDIT_DIALOG      152
#define IDD_DEPARTMENT_ADD_DIALOG       154
#define IDD_DEPARTMENT_FUNCTION_DIALOG  155
#define IDC_LOGIN                       1000
#define IDC_BIOGRAPHY                   1000
#define IDC_Password                    1001
#define IDC_CURRICULUM                  1001
#define IDC_FACULTY                     1001
#define IDC_FACULTY_ID                  1001
#define IDC_QUIT                        1002
#define IDC_FACULTY_NAME_THAI           1002
#define IDC_SERVICE                     1003
#define IDC_CLASS                       1003
#define IDC_FACULTY_NAME_ENG            1003
#define IDC_FEE                         1004
#define IDC_FACULTY_DESCRIPTION         1004
#define IDC_INFORMATION                 1004
#define IDC_ADD                         1005
#define IDC_REGISTER                    1005
#define IDC_MSFLEXGRID1                 1005
#define IDC_REMOVE                      1006
#define IDC_STDADD_TITLETHAI1           1006
#define IDC_STDID                       1006
#define IDC_SUBJECT                     1006
#define IDC_DEPARTMENT_FACULTY_NAME     1006
#define IDC_CHECK                       1007
#define IDC_STDADD_TITLETHAI2           1007
#define IDC_NAME                        1007
#define IDC_STDADD_TITLETHAI3           1008
#define IDC_DEPARTMENT                  1008
#define IDC_EDIT                        1008
#define IDC_RETURN                      1009
#define IDC_STDADD_NAMETHAI             1009
#define IDC_CODE1                       1009
#define IDC_STDADD_TITLEENG1            1010
#define IDC_CODE2                       1010
#define IDC_EDIT3                       1011
#define IDC_STDADD_SURNAMETHAI          1011
#define IDC_CURRICULUM_NAME_THAI        1011
#define IDC_EDIT2                       1011
#define IDC_DELETEFACULTY               1011
#define IDC_STDADD_TITLEENG2            1012
#define IDC_UPDATEFACULTY               1012
#define IDC_STDADD_TITLEENG3            1013
#define IDC_EXITFACULTY                 1013
#define IDC_STDADD_NAMETHAI2            1014
#define IDC_STDADD_NAMEENG              1014
#define IDC_EDIT4                       1015
#define IDC_STDADD_SURNAMEENG           1015
#define IDC_CURRICULUM_NAME_ENG         1015
#define IDC_EDIT5                       1015
#define IDC_DEPARTMENT_ID               1015
#define IDC_BUTTON1                     1016
#define IDC_STDEDIT_PREVIOUS            1016
#define IDC_DEPARTMENT_NAME_THAI        1016
#define IDC_BUTTON2                     1017
#define IDC_STDEDIT_NEXT                1017
#define IDC_MOVE_NEXT                   1017
#define IDC_DEPARTMENT_NAME_ENG         1017
#define IDC_SELECTNAME                  1018
#define IDC_FACULTY_COMBO               1018
#define IDC_STDEDIT_NAMETHAI            1019
#define IDC_DEPARTMENT_DESCRIPTION      1019
#define IDC_STDEDIT_NAMEENG             1020
#define IDC_ADDDEPARTMENT               1020
#define IDC_STDEDIT_SURNAMETHAI         1021
#define IDC_DELETEDEPARTMENT            1021
#define IDC_STDEDIT_SURNAMEENG          1022
#define IDC_UPDATEDEPARTMENT            1022
#define IDC_EXITDEPARTMENT              1023
#define IDC_FACULTYCOMBO                1026
#define IDC_STDEDIT_NO                  1030
#define IDC_STDEDIT_TITLETHAI           1031
#define IDC_STDEDIT_TITLEENG            1032
#define IDC_STDEDIT_SEX                 1033
#define IDC_STDEDIT_BIRTHDAY            1034
#define IDC_SUBJECT_ID                  1034
#define IDC_STDEDIT_RELIGIONCOMBO       1035
#define IDC_SUBJECT_NAME_THAI           1035
#define IDC_DEPTCOMBO                   1036
#define IDC_SUBJECT_NAME_ENG            1036
#define IDC_DEPT_NAME_THAI              1037
#define IDC_YEAR_STUDY                  1037
#define IDC_MAJOR_COMBO                 1038
#define IDC_CATEGORY                    1038
#define IDC_TERM_STUDY2                 1038
#define IDC_MAJOR_NAME_THAI             1039
#define IDC_GROUP                       1039
#define IDC_STDEDIT_NATIONCOMBO         1040
#define IDC_SUBJECT_SUM_CREDIT          1040
#define IDC_STD_NO                      1041
#define IDC_STDEDITCITIZENCOMBO         1041
#define IDC_STDADD_NO                   1041
#define IDC_SUBJECT_FACULTY_ID          1041
#define IDC_STDEDIT_ADDRNO              1042
#define IDC_SUBJECT_LEC_CREDIT          1042
#define IDC_STDEDIT_ADDRSOI             1043
#define IDC_SUBJECT_LAB_CREDIT          1043
#define IDC_SEARCH_ID                   1044
#define IDC_SUBJECT_FACULTY             1044
#define IDC_NATIONCOMBO                 1045
#define IDC_STDEDIT_ADDRROAD            1045
#define IDC_STDADD_NATION               1045
#define IDC_SUBJECT_DEPT                1045
#define IDC_SEX_MALE                    1046
#define IDC_STDEDIT_ADDRDISTINCT        1046
#define IDC_SUBJECT_DEPT_ID             1046
#define IDC_SEX_FEMALE                  1047
#define IDC_STDEDIT_ADDRBORDER          1047
#define IDC_SUBJECT_DESCRIPTION         1047
#define IDC_CITIZENCOMBO                1048
#define IDC_STDEDIT_ADDRPROVINCE        1048
#define IDC_STDADD_CITIZEN              1048
#define IDC_SUBJECT_MSFLEXGRID          1048
#define IDC_STDEDIT_ADDRCODE            1049
#define IDC_DELETE_SUBJECT              1049
#define IDC_BIRTHDAY                    1050
#define IDC_STDEDIT_ADDRTEL             1050
#define IDC_STDADD_BIRTHDAY             1050
#define IDC_EXIT_SUBJECT                1050
#define IDC_STDEDIT_ADDRFAX             1051
#define IDC_CURRICULUM_ID               1051
#define IDC_RELIGIONCOMBO               1052
#define IDC_STDEDIT_ADDRPAGER           1052
#define IDC_STDADD_RELIGION             1052
#define IDC_SUM_CREDIT                  1052
#define IDC_TEACHER_IDCOMBO             1053
#define IDC_SUBJ_SPECIFIC_CATEGORY_CREDIT 1053
#define IDC_STDEDIT_CADDRNO             1054
#define IDC_SUBJ_GENERAL_CATEGORY_CREDIT 1054
#define IDC_TEACHER_NAME                1055
#define IDC_SUBJ_ELECTIVE_CATEGORY_CREDIT 1055
#define IDC_TEACHER_SNAME               1056
#define IDC_SUBJECT_CATEGORY            1056
#define IDC_EDIT7                       1057
#define IDC_SUBJECT_GROUP               1057
#define IDC_ADDRNO                      1058
#define IDC_STDEDIT_CADDRSOI            1058
#define IDC_STDADD_ADDRNO               1058
#define IDC_ADDRSOI                     1059
#define IDC_STDEDIT_CADDRROAD           1059
#define IDC_STDADD_ADDRSOI              1059
#define IDC_ROOM_ID                     1059
#define IDC_ADDRROAD                    1060
#define IDC_STDEDIT_CADDRDISTINCT       1060
#define IDC_STDADD_ADDRROAD             1060
#define IDC_COMBO1                      1060
#define IDC_ADDRDISTINCT                1061
#define IDC_STDEDIT_CADDRBORDER         1061
#define IDC_STDADD_ADDRDISTINCT         1061
#define IDC_EDIT6                       1061
#define IDC_ADDRBORDER                  1062
#define IDC_STDEDIT_CADDRPROVINCE       1062
#define IDC_STDADD_ADDRBORDER           1062
#define IDC_EDIT8                       1062
#define IDC_ADDRPROVINCE                1063
#define IDC_STDEDIT_CADDRCODE           1063
#define IDC_STDADD_ADDRPROVINCE         1063
#define IDC_ADDROOM                     1063
#define IDC_ADDRCODE                    1064
#define IDC_STDEDIT_CADDRTEL            1064
#define IDC_STDADD_ADDRCODE             1064
#define IDC_DELETEROOM                  1064
#define IDC_ADDRTEL                     1065
#define IDC_STDEDIT_CADDRFAX            1065
#define IDC_STDADD_ADDRTEL              1065
#define IDC_UPDATEROOM                  1065
#define IDC_ADDRFAX                     1066
#define IDC_STDADD_ADDRFAX              1066
#define IDC_CURRICULUM_MSFLEXGRID       1066
#define IDC_ADDRPAGER                   1067
#define IDC_STDADD_ADDRPAGER            1067
#define IDC_CADDRNO                     1068
#define IDC_STDADD_CADDRNO              1068
#define IDC_SUBJECT_NAME                1068
#define IDC_CADDRROAD                   1069
#define IDC_STDADD_CADDRROAD            1069
#define IDC_CADDRBORDER                 1070
#define IDC_STDADD_CADDRBORDER          1070
#define IDC_ADD_CURRICULUM              1070
#define IDC_CADDRCODE                   1071
#define IDC_STDADD_CADDRCODE            1071
#define IDC_UPDATE_CURRICULUM           1071
#define IDC_CADDRFAX                    1072
#define IDC_STDADD_CADDRFAX             1072
#define IDC_DELETE_CURRICULUM           1072
#define IDC_CADDRSOI                    1073
#define IDC_STDADD_CADDRSOI             1073
#define IDC_CADDRDISTINCT               1074
#define IDC_STDADD_CADDRDISTINCT        1074
#define IDC_CADDRPROVINCE               1075
#define IDC_STDADD_CADDRPROVINCE        1075
#define IDC_BUTTON6                     1075
#define IDC_CADDRTEL                    1076
#define IDC_STDADD_CADDRTEL             1076
#define IDC_REGISTER_TITLETHAI1         1076
#define IDC_STDADD_TITLETHAI            1077
#define IDC_REGISTER_TITLETHAI2         1077
#define IDC_STDADD_TITLEENG             1078
#define IDC_REGISTER_TITLETHAI3         1078
#define IDC_STDADD_SEX                  1079
#define IDC_REGISTER_NAMETHAI           1079
#define IDC_STDADD_FACULTYCOMBO         1080
#define IDC_REGISTER_SURNAMETHAI        1080
#define IDC_STDADD_FACULTYNAMETHAI      1081
#define IDC_STDADD_DEPTCOMBO            1082
#define IDC_STDADD_DEPTNAMETHAI         1083
#define IDC_TERM_STUDY                  1083
#define IDC_STDADD_MAJORCOMBO           1084
#define IDC_STDADD_MAJORNAMETHAI        1085
#define IDC_LAC_CREDIT                  1086
#define IDC_LEC_CREDIT                  1086
#define IDC_STDADD_TEACHERID            1087
#define IDC_LAC_CREDIT2                 1087
#define IDC_LAB_CREDIT                  1087
#define IDC_STDADD_TEACHERTITLE         1088
#define IDC_LAC_CREDIT3                 1088
#define IDC_STDADD_TEACHERNAME          1089
#define IDC_ADD_REGISTER_SUBJECT        1089
#define IDC_STDADD_TEACHERSURNAME       1090
#define IDC_DELETE_REGISTER_SUBJECT     1090
#define IDC_ALL                         1091
#define IDC_REGISTER_MSFLEXGRID         1091
#define IDC_CONFIRM_REGISTER            1092
#define IDC_STUDENT_CURRICULUM          1093
#define IDC_STUDENTID                   1093
#define IDC_STUDENT_LEVEL               1094
#define IDC_STUDENT_CODE                1095
#define IDC_CURRICULUM_FACULTY_ID       1095
#define IDC_CURRICULUM_DEPT_ID          1097
#define IDC_CURRICULUM_DEPT_NAME_THAI   1098
#define IDC_CURRICULUM_FACULTY_NAME_THAI 1099
#define IDC_MOVE_PREV                   1100
#define IDC_EDITSUBJECT                 1101
#define IDC_TITLE_NAME                  1102
#define IDC_ACADEMIC_YEAR               1103
#define IDC_TERM                        1104
#define ID_OK                           1105
#define IDC_BUTTON10                    1107
#define IDC_ADDFACULTY                  1107
#define IDC_EDIT_FACULTY                1108
#define IDC_FACULTY_ADD                 1109
#define IDC_FACULTY_EDIT_DIALOG         1110
#define IDC_MOVE_PREVIOUS               1111
#define IDC_DEPT_MOVE_NEXT              1112

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        156
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1112
#define _APS_NEXT_SYMED_VALUE           106
#endif
#endif
