//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Mapper.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_MAPPERTYPE                  129
#define IDD_BLOCKSTATUS                 131
#define IDC_I                           1000
#define IDC_J                           1001
#define IDC_TYPE                        1002
#define IDC_LEVEL                       1003
#define IDC_RESERVED                    1004

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        133
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1005
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
