Create Table RegisterCard
( Regis_No           int  not null,
  Regis_Std_Id       char(8)  null,
  Regis_Year         char(4)  null,
  Regis_Term         char(1)  null,
  Regis_Type         char(1)  null,
  Regis_Date         datetime null,
  Regis_Pay_Type     char(50) null,
  Std_Pay_Type       char(50) null,
  Bill_Book_No       char(4)  null,
  Bill_Order_No      char(4)  null,
  Bill_Date          datetime null,
  Fee_Type1          int   null,
  Fee_Type2          int   null,
  Fee_Type3          int   null,
  Fee_Type4          int   null,
  Fee_Type5          int   null,
  Fee_Type6          int   null,
  Fee_Type7          int   null,
  Fee_Type8          int   null,
  Fee_Type9          int   null,
  Fee_Type10         int   null,
  Fee_Type11         int   null,
  Fee_Type12         int   null,
  Paid_Bank_Name     char(20) null,
  Paid_Bank_Branch   char(30) null,
  Paid_Bank_Check_No char(4)  null,

Constraint PKregistercard primary key (Regis_No))