Create table Project97.dbo.student
( Std_Id			Char 	(8) 	not null,
  Std_Title_Thai		Char	(6) 	null,
  Std_Name_Thai		Char	(15)	null,
  Std_Sname_Thai		Char	(25) 	null,
  Std_Title_Eng		Char	(6)	null,
  Std_Name_Eng		Char	(15) 	null,
  Std_Sname_Eng		Char	(25) 	null,
  Std_Birthday		Datetime		null,
  Std_Sex			Char	(1)	null,
  Std_Nation 		Char	(15)	null,
  Std_Citizen		Char 	(15) 	null,
  Std_Religion 		Char 	(15)	null,
  Std_Blood		Char 	(3)	null,
  Std_Height		Real		null,
  Std_Weight		Real		null,
  Std_Addr_No		Char	(10)	null,
  Std_Addr_Soi		Char	(15)	null,
  Std_Addr_Road		Char	(15)	null,  
  Std_Addr_District		Char	(15)	null, 
  Std_Addr_Border		Char	(15)	null, 
  Std_Addr_Province	Char	(15)	null,  
  Std_Addr_Code		Char	(5)	null,  
  Std_Addr_Tel		Char	(15)	null, 
  Std_Addr_Fax		Char	(15)	null,
  Std_Taddr_No		Char	(10)	null,
  Std_Taddr_Soi		Char	(15)	null,
  Std_Taddr_Road		Char	(15)	null,  
  Std_Taddr_District	Char	(15)	null, 
  Std_Taddr_Border		Char	(15)	null, 
  Std_Taddr_Province	Char	(15)	null,  
  Std_Taddr_Code		Char	(5)	null,  
  Std_Taddr_Tel		Char	(15)	null, 
  Std_Taddr_Fax		Char	(15)	null,
  Std_Pregrad		Char	(5)	null,
  Std_School_Name		Char	(50)	null,
  Std_School_Situated	Char	(15)	null,
  Std_School_GPA		Real		null, 
  Std_School_Admission	Datetime		null,
  Std_School_Finish	Datetime		null,
  Std_Entype		Char	(2) 	null,
  Std_Campus		Char	(1)	null,
  Std_Major_Id		Char	(3)	null,
  Std_Minor_Id		Char	(3)	null,
  Std_Status		Char	(1)	null,
  Std_Resign_Datetime	Datetime		null,
  Par_Id			Char	(8) 	null,
  Dad_Id			Char	(8)	null,
  Mom_Id			Char	(8)	null,
  Teacher_Id		Char	(8)	null,
  Dept_Id			Char	(3) 	null,
  Faculty_Id                    Char    (2)     null,
  Curiculum_Id		Char	(2)	null,
  Std_total_Cradit		Char	(5)	null,
  Std_Year_Enter		Char	(4)	null,
  Std_Bank_Acc_No		Char	(10)	null,
  YearStudy             Char    (1)     null, 

Constraint PKstudent primary key (std_Id)
 )