public class Code  {
    public static final int SIZE=6;
    public static final double codeA[]={0,0,0,0,0,1};
    public static final double codeB[]={0,0,0,0,1,0};
    public static final double codeC[]={0,0,0,0,1,1};
    public static final double codeD[]={0,0,0,1,0,0};
    public static final double codeE[]={0,0,0,1,0,1};
    public static final double codeF[]={0,0,0,1,1,0};
    public static final double codeG[]={0,0,0,1,1,1};
    public static final double codeH[]={0,0,1,0,0,0};
    public static final double codeI[]={0,0,1,0,0,1};
    public static final double codeJ[]={0,0,1,0,1,0};
    public static final double codeK[]={0,0,1,0,1,1};
    public static final double codeL[]={0,0,1,1,0,0};
    public static final double codeM[]={0,0,1,1,0,1};
    public static final double codeN[]={0,0,1,1,1,0};
    public static final double codeO[]={0,0,1,1,1,1};
    public static final double codeP[]={0,1,0,0,0,0};
    public static final double codeQ[]={0,1,0,0,0,1};
    public static final double codeR[]={0,1,0,0,1,0};
    public static final double codeS[]={0,1,0,0,1,1};
    public static final double codeT[]={0,1,0,1,0,0};
    public static final double codeU[]={0,1,0,1,0,1};
    public static final double codeV[]={0,1,0,1,1,0};
    public static final double codeW[]={0,1,0,1,1,1};
    public static final double codeX[]={0,1,1,0,0,0};
    public static final double codeY[]={0,1,1,0,0,1};
    public static final double codeZ[]={0,1,1,0,1,0};
    public static final double codea[]={0,1,1,0,1,1};
    public static final double codeb[]={0,1,1,1,0,0};
    public static final double codec[]={0,1,1,1,0,1};
    public static final double coded[]={0,1,1,1,1,0};
    public static final double codee[]={0,1,1,1,1,1};
    public static final double codef[]={1,0,0,0,0,0};
    public static final double codeg[]={1,0,0,0,0,1};
    public static final double codeh[]={1,0,0,0,1,0};
    public static final double codei[]={1,0,0,0,1,1};
    public static final double codej[]={1,0,0,1,0,0};
    public static final double codek[]={1,0,0,1,0,1};
    public static final double codel[]={1,0,0,1,1,0};
    public static final double codem[]={1,0,0,1,1,1};
    public static final double coden[]={1,0,1,0,0,0};
    public static final double codeo[]={1,0,1,0,0,1};
    public static final double codep[]={1,0,1,0,1,0};
    public static final double codeq[]={1,0,1,0,1,1};
    public static final double coder[]={1,0,1,1,0,0};
    public static final double codes[]={1,0,1,1,0,1};
    public static final double codet[]={1,0,1,1,1,0};
    public static final double codeu[]={1,0,1,1,1,1};
    public static final double codev[]={1,1,0,0,0,0};
    public static final double codew[]={1,1,0,0,0,1};
    public static final double codex[]={1,1,0,0,1,0};
    public static final double codey[]={1,1,0,0,1,1};
    public static final double codez[]={1,1,0,1,0,0};
    public static final double code1[]={1,1,0,1,0,1};
    public static final double code2[]={1,1,0,1,1,0};
    public static final double code3[]={1,1,0,1,1,1};
    public static final double code4[]={1,1,1,0,0,0};
    public static final double code5[]={1,1,1,0,0,1};
    public static final double code6[]={1,1,1,0,1,0};
    public static final double code7[]={1,1,1,0,1,1};
    public static final double code8[]={1,1,1,1,0,0};
    public static final double code9[]={1,1,1,1,0,1};
    public static final double code0[]={1,1,1,1,1,0};
    
    public static final double codeError[]={0,0,0,0,0,0};

    public static String decode(double[] code) {
       if(checkMatch(code,codeA)) return "A";
       if(checkMatch(code,codeB)) return "B";
       if(checkMatch(code,codeC)) return "C";
       if(checkMatch(code,codeD)) return "D";
       if(checkMatch(code,codeE)) return "E";
       if(checkMatch(code,codeF)) return "F";
       if(checkMatch(code,codeG)) return "G";
       if(checkMatch(code,codeH)) return "H";
       if(checkMatch(code,codeI)) return "I";
       if(checkMatch(code,codeJ)) return "J";
       if(checkMatch(code,codeK)) return "K";
       if(checkMatch(code,codeL)) return "L";
       if(checkMatch(code,codeM)) return "M";
       if(checkMatch(code,codeN)) return "N";
       if(checkMatch(code,codeO)) return "O";
       if(checkMatch(code,codeP)) return "P";
       if(checkMatch(code,codeQ)) return "Q";
       if(checkMatch(code,codeR)) return "R";
       if(checkMatch(code,codeS)) return "S";
       if(checkMatch(code,codeT)) return "T";
       if(checkMatch(code,codeU)) return "U";
       if(checkMatch(code,codeV)) return "V";
       if(checkMatch(code,codeW)) return "W";
       if(checkMatch(code,codeX)) return "X";
       if(checkMatch(code,codeY)) return "Y";
       if(checkMatch(code,codeZ)) return "Z";
       if(checkMatch(code,codea)) return "a";
       if(checkMatch(code,codeb)) return "b";
       if(checkMatch(code,codec)) return "c";
       if(checkMatch(code,coded)) return "d";
       if(checkMatch(code,codee)) return "e";
       if(checkMatch(code,codef)) return "f";
       if(checkMatch(code,codeg)) return "g";
       if(checkMatch(code,codeh)) return "h";
       if(checkMatch(code,codei)) return "i";
       if(checkMatch(code,codej)) return "j";
       if(checkMatch(code,codek)) return "k";
       if(checkMatch(code,codel)) return "l";
       if(checkMatch(code,codem)) return "m";
       if(checkMatch(code,coden)) return "n";
       if(checkMatch(code,codeo)) return "o";
       if(checkMatch(code,codep)) return "p";
       if(checkMatch(code,codeq)) return "q";
       if(checkMatch(code,coder)) return "r";
       if(checkMatch(code,codes)) return "s";
       if(checkMatch(code,codet)) return "t";
       if(checkMatch(code,codeu)) return "u";
       if(checkMatch(code,codev)) return "v";
       if(checkMatch(code,codew)) return "w";
       if(checkMatch(code,codex)) return "x";
       if(checkMatch(code,codey)) return "y";
       if(checkMatch(code,codez)) return "z";
       if(checkMatch(code,code1)) return "1";
       if(checkMatch(code,code2)) return "2";
       if(checkMatch(code,code3)) return "3";
       if(checkMatch(code,code4)) return "4";
       if(checkMatch(code,code5)) return "5";
       if(checkMatch(code,code6)) return "6";
       if(checkMatch(code,code7)) return "7";
       if(checkMatch(code,code8)) return "8";
       if(checkMatch(code,code9)) return "9";
       if(checkMatch(code,code0)) return "0";

       else return "Error";
    }

    public static boolean checkMatch(double code1[],double code2[]) {
        if(code1.length!=code2.length) return false;
        for(int i=0;i<code1.length;i++)
           if(code1[i]!=code2[i])  return false;
        return true;
    }

    public static double[] encode(String code) {
       if(code.equals("A")) return codeA;
       if(code.equals("B")) return codeB;
       if(code.equals("C")) return codeC;
       if(code.equals("D")) return codeD;
       if(code.equals("E")) return codeE;
       if(code.equals("F")) return codeF;
       if(code.equals("G")) return codeG;
       if(code.equals("H")) return codeH;
       if(code.equals("I")) return codeI;
       if(code.equals("J")) return codeJ;
       if(code.equals("K")) return codeK;
       if(code.equals("L")) return codeL;
       if(code.equals("M")) return codeM;
       if(code.equals("N")) return codeN;
       if(code.equals("O")) return codeO;
       if(code.equals("P")) return codeP;
       if(code.equals("Q")) return codeQ;
       if(code.equals("R")) return codeR;
       if(code.equals("S")) return codeS;
       if(code.equals("T")) return codeT;
       if(code.equals("U")) return codeU;
       if(code.equals("V")) return codeV;
       if(code.equals("W")) return codeW;
       if(code.equals("X")) return codeX;
       if(code.equals("Y")) return codeY;
       if(code.equals("Z")) return codeZ;
       if(code.equals("a")) return codea;
       if(code.equals("b")) return codeb;
       if(code.equals("c")) return codec;
       if(code.equals("d")) return coded;
       if(code.equals("e")) return codee;
       if(code.equals("f")) return codef;
       if(code.equals("g")) return codeg;
       if(code.equals("h")) return codeh;
       if(code.equals("i")) return codei;
       if(code.equals("j")) return codej;
       if(code.equals("k")) return codek;
       if(code.equals("l")) return codel;
       if(code.equals("m")) return codem;
       if(code.equals("n")) return coden;
       if(code.equals("o")) return codeo;
       if(code.equals("p")) return codep;
       if(code.equals("q")) return codeq;
       if(code.equals("r")) return coder;
       if(code.equals("s")) return codes;
       if(code.equals("t")) return codet;
       if(code.equals("u")) return codeu;
       if(code.equals("v")) return codev;
       if(code.equals("w")) return codew;
       if(code.equals("x")) return codex;
       if(code.equals("y")) return codey;
       if(code.equals("z")) return codez;
       if(code.equals("1")) return code1;
       if(code.equals("2")) return code2;
       if(code.equals("3")) return code3;
       if(code.equals("4")) return code4;
       if(code.equals("5")) return code5;
       if(code.equals("6")) return code6;
       if(code.equals("7")) return code7;
       if(code.equals("8")) return code8;
       if(code.equals("9")) return code9;
       if(code.equals("0")) return code0;

       else return  codeError;
    }

}
