<HTML>
<HEAD><TITLE>Result</TITLE></HEAD>
<BODY BGCOLOR="FFFFFF">
<Center>
<TABLE  Border=1 Cellspacing=1>
<TR>
<TH Bgcolor=GREEN><Font Size=2 Color=White><B>หมายเลขยานพาหนะ</B></Font></TH>
<TH Bgcolor=GREEN><Font Size=2 Color=White><B>ชนิดของพาหนะ</B></Font></TH>
</TR>
<%begindetail%>
<TR><TD><%id_vehicle1%></TD><TD align="right"><%Type_vehicle1%></TD></TR>
<%enddetail%>
</TABLE>
</Center>
</BODY>
</HTML>
