<html>
<head>
<Title>Statistic</title>
</head>
<body background="note.gif">
<hr>
<p><b><big><font size="6">Please type date in this format mm/dd/yy</font> </big></b>
<form action="Show_stat.asp" method= "post" style="BACKGROUND-IMAGE: url(file://E:\Project\note.gif)">
 <table width="75%" border="0">
    <tr>
      <td width="17%"><font size="5">From :</font></td>
      <td width="83%"><font size="5"> 
        <input name="day1" size="8" maxlength="8" >
        </font></td>
    </tr>
    <tr>
      <td width="17%"><font size="5">To :</font></td>
      <td width="83%"><font size="5"> 
        <input name="day2" size="8" maxlength="8" >
        </font></td>
    </tr>
  </table><p><font size="5">
    <input type="submit" name="Submit" value="Submit">
    </font> </p>
</form>
</body>
</html>
