#!/usr/bin/perl -w

$Detail = $ENV{'DAILYCHECK_DETAIL_LEVEL'};

while (defined($ThisLine = <STDIN>)) {
    if ( $ThisLine =~ s/^can\'t locate module (.*)$/$1/ ) {
	chomp($ThisLine);
	$Modules{$ThisLine}++;
    }
    else {
	# Report any unmatched entries...
	push @OtherList,$ThisLine;
    }
}

if ( ($#OtherList >= 0) or (keys(%Modules)) ) {

    if ( ($Detail >= 10) or ($#OtherList >= 0) ) {

	print "\n\n --------------------- ModProbe Begin ------------------------ \n";
    
	if ( $Detail >= 10 ) {
	    print "\nCan't locate these modules:\n";
	    foreach $ThisOne (keys %Modules) {
		print "   " . $ThisOne . ": " . $Modules{$ThisOne} . " Time(s)\n";
	    }
	}
	
	if ($#OtherList >= 0) {
	    print "\n**Unmatched Entries**\n";
	    print @OtherList;
	}
	
	print "\n\n ---------------------- ModProbe End ------------------------- \n\n";

    }
    
}

exit(0);



