#!/usr/bin/perl -w

while (defined($ThisLine = <STDIN>)) {
    $ThisLine =~ s/^... .. ..:..:.. [^ ]* [^ ]*\[[0123456789]*\]: //;
    $ThisLine =~ s/^... .. ..:..:.. [^ ]* [^ ]*: //;
    print $ThisLine;
}
