drop table PROJ_LAYOUT;
drop table LAYOUT;
drop table ANDGATE;
drop table ORGATE;
drop table NOTGATE;
drop table XORGATE;
drop table XNORGATE;
drop table NANDGATE;
drop table NORGATE;
drop table NEWGATE;
drop table WIRED;
drop row type WIRED restrict;
drop row type AND restrict;
drop row type OR restrict;
drop row type NOT restrict;
drop row type XOR restrict;
drop row type XNOR restrict;
drop row type NAND restrict;
drop row type NOR restrict;
drop row type NEW restrict;
drop row type GATE restrict;