//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by SnmpAgent.rc
//
#define IDD_ABOUTBOX                    100
#define BAD_TAG_VALUE                   101
#define BAD_LENGTH_VALUE                102
#define BAD_VERSION_FORMAT              103
#define IDP_SOCKETS_INIT_FAILED         104
#define BAD_VERSION_VALUE               104
#define BAD_COMMUNITY_NAME_FORMAT       105
#define BAD_COMMUNITY_NAME_VALUE        106
#define BAD_PDU_FORMAT                  107
#define BAD_PDU_LENGTH                  108
#define BAD_REQUEST_ID_FORMAT           109
#define BAD_ERROR_STATUS_FORMAT         113
#define INVALID_ERROR_STATUS_RCVD       114
#define BAD_ERROR_INDEX_FORMAT          115
#define INVALID_ERROR_INDEX_RCVD        116
#define BAD_VARBINDLIST_TAG_VALUE       117
#define BAD_VARBINDLIST_TAG_LENGTH      118
#define BAD_VARIABLE_TAG_VALUE          119
#define BAD_OID_TAG_VALUE               120
#define SNMP_MESSAGE_OK                 121
#define IDR_MAINFRAME                   128
#define IDR_SNMPAGTYPE                  129

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        130
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           122
#endif
#endif
