// MD5.cpp: implementation of the CMD5 class.
//
//////////////////////////////////////////////////////////////////////

#include "stdafx.h"
#include "SecureShell.h"
#include "MD5.h"

#ifdef _DEBUG
#undef THIS_FILE
static char THIS_FILE[]=__FILE__;
#define new DEBUG_NEW
#endif

//////////////////////////////////////////////////////////////////////
// Construction/Destruction
//////////////////////////////////////////////////////////////////////

const int CMD5::HASH_LENGTH = 16;
const int CMD5::DATA_LENGTH = 64;

CMD5::CMD5() : CMessageDigest()
{
	BufferSetSize(Data_Length());
	MD5_Init();
	Reset();
}

void CMD5::MD5_Init()
{
	Digest	= new CUIntArray();
	Digest->SetSize(HASH_LENGTH/4);
	Data	= new CUIntArray();
	Data->SetSize(DATA_LENGTH/4);
	Temp	= new CByteArray();
	Temp->SetSize(DATA_LENGTH);

}


CMD5::~CMD5()
{

}

void CMD5::MD_Reset()
{
	Digest->SetAt(0,0x67452301);
	Digest->SetAt(1,0xefcdab89);
	Digest->SetAt(2,0x98badcfe);
	Digest->SetAt(3,0x10325476);
}



void CMD5::MD_Transform()
{
	byte2int(Data, 0, Buffer(), 0, DATA_LENGTH/4);
	Transform(Data);
	
}

void CMD5::byte2int(CUIntArray* dst, int dst_off, CByteArray* src, int src_off, int len)
{
	while (len-- > 0)
	{
		// Little endian
		dst->SetAt(dst_off++, ((src->GetAt(src_off++) & 0xFF) | ((src->GetAt(src_off++) << 8) & 0xFF00)
				| ((src->GetAt(src_off++) << 16) & 0xFF0000) | ((src->GetAt(src_off++) << 24))));
	}
	
}



void CMD5::Transform(CUIntArray* M)
{
		UINT a,b,c,d;

		a = Digest->GetAt(0);
		b = Digest->GetAt(1);
		c = Digest->GetAt(2);
		d = Digest->GetAt(3);

		a = FF(a,b,c,d,M->GetAt(0), 7,0xd76aa478);
		d = FF(d,a,b,c,M->GetAt(1),12,0xe8c7b756);
		c = FF(c,d,a,b,M->GetAt(2),17,0x242070db);
		b = FF(b,c,d,a,M->GetAt(3),22,0xc1bdceee);
		a = FF(a,b,c,d,M->GetAt(4), 7,0xf57c0faf);
		d = FF(d,a,b,c,M->GetAt(5),12,0x4787c62a);
		c = FF(c,d,a,b,M->GetAt(6),17,0xa8304613);
		b = FF(b,c,d,a,M->GetAt(7),22,0xfd469501);
		a = FF(a,b,c,d,M->GetAt(8), 7,0x698098d8);
		d = FF(d,a,b,c,M->GetAt(9),12,0x8b44f7af);
		c = FF(c,d,a,b,M->GetAt(10),17,0xffff5bb1);
		b = FF(b,c,d,a,M->GetAt(11),22,0x895cd7be);
		a = FF(a,b,c,d,M->GetAt(12), 7,0x6b901122);
		d = FF(d,a,b,c,M->GetAt(13),12,0xfd987193);
		c = FF(c,d,a,b,M->GetAt(14),17,0xa679438e);
		b = FF(b,c,d,a,M->GetAt(15),22,0x49b40821);

		a = GG(a,b,c,d,M->GetAt(1), 5,0xf61e2562);
		d = GG(d,a,b,c,M->GetAt(6), 9,0xc040b340);
		c = GG(c,d,a,b,M->GetAt(11),14,0x265e5a51);
		b = GG(b,c,d,a,M->GetAt(0),20,0xe9b6c7aa);
		a = GG(a,b,c,d,M->GetAt(5), 5,0xd62f105d);
		d = GG(d,a,b,c,M->GetAt(10), 9,0x02441453);
		c = GG(c,d,a,b,M->GetAt(15),14,0xd8a1e681);
		b = GG(b,c,d,a,M->GetAt(4),20,0xe7d3fbc8);
		a = GG(a,b,c,d,M->GetAt(9), 5,0x21e1cde6);
		d = GG(d,a,b,c,M->GetAt(14), 9,0xc33707d6);
		c = GG(c,d,a,b,M->GetAt(3),14,0xf4d50d87);
		b = GG(b,c,d,a,M->GetAt(8),20,0x455a14ed);
		a = GG(a,b,c,d,M->GetAt(13), 5,0xa9e3e905);
		d = GG(d,a,b,c,M->GetAt(2), 9,0xfcefa3f8);
		c = GG(c,d,a,b,M->GetAt(7),14,0x676f02d9);
		b = GG(b,c,d,a,M->GetAt(12),20,0x8d2a4c8a);

		a = HH(a,b,c,d,M->GetAt( 5), 4,0xfffa3942);
		d = HH(d,a,b,c,M->GetAt( 8),11,0x8771f681);
		c = HH(c,d,a,b,M->GetAt(11),16,0x6d9d6122);
		b = HH(b,c,d,a,M->GetAt(14),23,0xfde5380c);
		a = HH(a,b,c,d,M->GetAt( 1), 4,0xa4beea44);
		d = HH(d,a,b,c,M->GetAt( 4),11,0x4bdecfa9);
		c = HH(c,d,a,b,M->GetAt( 7),16,0xf6bb4b60);
		b = HH(b,c,d,a,M->GetAt(10),23,0xbebfbc70);
		a = HH(a,b,c,d,M->GetAt(13), 4,0x289b7ec6);
		d = HH(d,a,b,c,M->GetAt( 0),11,0xeaa127fa);
		c = HH(c,d,a,b,M->GetAt( 3),16,0xd4ef3085);
		b = HH(b,c,d,a,M->GetAt( 6),23,0x04881d05);
		a = HH(a,b,c,d,M->GetAt( 9), 4,0xd9d4d039);
		d = HH(d,a,b,c,M->GetAt(12),11,0xe6db99e5);
		c = HH(c,d,a,b,M->GetAt(15),16,0x1fa27cf8);
		b = HH(b,c,d,a,M->GetAt( 2),23,0xc4ac5665);

		a = II(a,b,c,d,M->GetAt( 0), 6,0xf4292244);
		d = II(d,a,b,c,M->GetAt( 7),10,0x432aff97);
		c = II(c,d,a,b,M->GetAt(14),15,0xab9423a7);
		b = II(b,c,d,a,M->GetAt( 5),21,0xfc93a039);
		a = II(a,b,c,d,M->GetAt(12), 6,0x655b59c3);
		d = II(d,a,b,c,M->GetAt( 3),10,0x8f0ccc92);
		c = II(c,d,a,b,M->GetAt(10),15,0xffeff47d);
		b = II(b,c,d,a,M->GetAt( 1),21,0x85845dd1);
		a = II(a,b,c,d,M->GetAt( 8), 6,0x6fa87e4f);
		d = II(d,a,b,c,M->GetAt(15),10,0xfe2ce6e0);
		c = II(c,d,a,b,M->GetAt( 6),15,0xa3014314);
		b = II(b,c,d,a,M->GetAt(13),21,0x4e0811a1);
		a = II(a,b,c,d,M->GetAt( 4), 6,0xf7537e82);
		d = II(d,a,b,c,M->GetAt(11),10,0xbd3af235);
		c = II(c,d,a,b,M->GetAt( 2),15,0x2ad7d2bb);
		b = II(b,c,d,a,M->GetAt( 9),21,0xeb86d391);

		Digest->SetAt(0,Digest->GetAt(0)+ a);
		Digest->SetAt(1,Digest->GetAt(1)+ b);
		Digest->SetAt(2,Digest->GetAt(2)+ c);
		Digest->SetAt(3,Digest->GetAt(3)+ d);



}

UINT CMD5::F(UINT x, UINT y, UINT z)
{
	return (z^(x & (y^z)));
}

UINT CMD5::G(UINT x, UINT y, UINT z)
{
	return (y^(z & (x^y)));
}	

UINT CMD5::H(UINT x, UINT y, UINT z)
{
	return (x^y^z);
}

UINT CMD5::I(UINT x, UINT y, UINT z)
{
	return (y^(x | ~z));
}

// ROTATE_LEFT rotates x left n bits
#define ROTATE_LEFT(x,n) (((x) << (n)) | ((x) >> (32-(n))))

UINT CMD5::FF(UINT a, UINT b, UINT c, UINT d, UINT k, UINT s, UINT t)
{
			a += k+t+F(b,c,d);
			a = ROTATE_LEFT((a),(s));
			return a+b;

}

UINT CMD5::GG(UINT a, UINT b, UINT c, UINT d, UINT k, UINT s, UINT t)
{
			a += k+t+G(b,c,d);
			a = ROTATE_LEFT((a),(s));
			return a+b;

}

UINT CMD5::HH(UINT a, UINT b, UINT c, UINT d, UINT k, UINT s, UINT t)
{
			a += k+t+H(b,c,d);
			a = ROTATE_LEFT((a),(s));
			return a+b;

}


UINT CMD5::II(UINT a, UINT b, UINT c, UINT d, UINT k, UINT s, UINT t)
{
			a += k+t+I(b,c,d);
			a = ROTATE_LEFT((a),(s));
			return a+b;

}



CByteArray* CMD5::MD_Digest()
{
	int pos = BufferOffset();
	if ( pos != 0)  
		for (int i=0;i<pos;i++)
			Temp->SetAt(i,Buffer()->GetAt(i));
	Temp->SetAt(pos++,-128);

	// if over 448 bits write zero to end block
	if ( pos > (DATA_LENGTH-8))
	{
		while (pos < DATA_LENGTH) Temp->SetAt(pos++,0);
		byte2int(Data,0,Temp,0,DATA_LENGTH/4);
		Transform(Data);
		pos = 0;
	}
	while (pos < (DATA_LENGTH-8)) Temp->SetAt(pos++,0);
	byte2int(Data, 0, Temp, 0, (DATA_LENGTH/4)-2);

	// Little endian
	Data->SetAt(14,(UINT)BitCount());
	Data->SetAt(15,(UINT)((BitCount() & 0x0000)>>32));

	Transform(Data);

	CByteArray* Buf = new CByteArray();
	Buf->SetSize(HASH_LENGTH);

	// Little endian
	int off = 0;
	for (int i=0;i<HASH_LENGTH/4;++i) {
		UINT d = Digest->GetAt(i);
		Buf->SetAt(off++,(BYTE) d);
		Buf->SetAt(off++,(BYTE)((d&0xffffff00)>>8));
		Buf->SetAt(off++,(BYTE)((d&0xffff0000)>>16));
		Buf->SetAt(off++,(BYTE)((d&0xff000000)>>24));
	}
	return Buf;

}

int CMD5::Data_Length()
{
	return CMD5::DATA_LENGTH;
}

int CMD5::Hash_Length()
{
	return CMD5::HASH_LENGTH;
}

CString CMD5::Name()
{
	CString name("MD5");
	return name;
}	


CByteArray* CMD5::Hash(CString message)
{
	return CMessageDigest::Hash(message, new CMD5() );
}

CByteArray* CMD5::Hash(CByteArray * message)
{
	return CMessageDigest::Hash(message, new CMD5());
}
