/****------- DECLARATION OF TOPICS USED BY TOPICS --------****/


#include <stdio.h>
#include "kpengine.h"
#include "STAT-EST.H"
TList TL2[] = // &Quit
{
  TList( NULL, NULL )
};
TList TL3[] = // &File
{
  TList( NULL, NULL )
};
TList TL7[] = // exp1
{
  TList( NULL, NULL )
};
TList TL8[] = // exp2
{
  TList( NULL, NULL )
};
TList TL9[] = // exp3
{
  TList( NULL, NULL )
};
TList TL10[] = // exp4
{
  TList( NULL, NULL )
};
TList TL11[] = // exp5
{
  TList( NULL, NULL )
};
TList TL12[] = // exp6
{
  TList( NULL, NULL )
};
TList TL13[] = // exp7
{
  TList( NULL, NULL )
};
TList TL14[] = // exp9
{
  TList( NULL, NULL )
};
TList TL15[] = // exp10
{
  TList( NULL, NULL )
};
TList TL16[] = // exp11
{
  TList( NULL, NULL )
};
TList TL17[] = // continue_ve
{
  TList( NULL, NULL )
};
TList TL6[] = // explain_TypeOfTesting
{
  TList( NULL, NULL )
};
TList TL5[] = // retu
{
  TList("item",NULL),
  TList( NULL, NULL )
};
TList TL4[] = // &Consultant
{
  TList( NULL, NULL )
};
TList TL19[] = // independence
{
  TList( NULL, NULL )
};
TList TL20[] = // equal_variance
{
  TList( NULL, NULL )
};
TList TL21[] = // distribution
{
  TList( NULL, NULL )
};
TList TL22[] = // NumberPopulation
{
  TList( NULL, NULL )
};
TList TL23[] = // KindOfTest1
{
  TList( NULL, NULL )
};
TList TL24[] = // KindOfTest2
{
  TList( NULL, NULL )
};
TList TL25[] = // variance_known
{
  TList( NULL, NULL )
};
TList TL26[] = // samplesize
{
  TList( NULL, NULL )
};
TList TL18[] = // TypeOfTesting
{
  TList( NULL, NULL )
};
TList TL1[] = // GetOption
{
  TList("item",NULL),
  TList( NULL, NULL )
};
TList TL27[] = // &Testing
{
  TList( NULL, NULL )
};
TList TL0[] = // !main
{
  TList( NULL, NULL )
};
