/* Student 1P */
Insert into Student(Std_Id,Std_Name_Eng,Std_Sname_Eng,Std_Entype,Dept_Id,Faculty_Id,Curiculum_Id,Std_Year_Enter,Std_Bank_Acc_No,YearStudy)
values('40013243','Kitti','Boonmee','20','107','01','19','2540','9101','1')


/* Student 2P */
Insert into Student(Std_Id,Std_Name_Eng,Std_Sname_Eng,Std_Entype,Dept_Id,Faculty_Id,Curiculum_Id,Std_Year_Enter,Std_Bank_Acc_No,YearStudy)
values('39013226','Kanokwut','Thanadkarn','20','107','01','19','2539','9201','2')


/* Student 3P */
Insert into Student(Std_Id,Std_Name_Eng,Std_Sname_Eng,Std_Entype,Dept_Id,Faculty_Id,Curiculum_Id,Std_Year_Enter,Std_Bank_Acc_No,YearStudy)
values('38013289','Withaya','Gaewrasameekul','20','107','01','19','2538','1903','3')

Insert into Student(Std_Id,Std_Name_Eng,Std_Sname_Eng,Std_Entype,Dept_Id,Faculty_Id,Curiculum_Id,Std_Year_Enter,Std_Bank_Acc_No,YearStudy)
values('38013301','Anuchit','Chansatirapanich','20','107','01','19','2538','1905','3')

Insert into Student(Std_Id,Std_Name_Eng,Std_Sname_Eng,Std_Entype,Dept_Id,Faculty_Id,Curiculum_Id,Std_Year_Enter,Std_Bank_Acc_No,YearStudy)
values('38013302','Anusorn','Luangrungsap','20','107','01','19','2538','1906','3')



/* Student 3D */ 
Insert into Student(Std_Id,Std_Name_Eng,Std_Sname_Eng,Std_Entype,Dept_Id,Faculty_Id,Curiculum_Id,Std_Year_Enter,Std_Bank_Acc_No,YearStudy)
values('38014097','Chayanee','Tangsukkasemsant','10','107','01','07','2538','7301','3')

Insert into Student(Std_Id,Std_Name_Eng,Std_Sname_Eng,Std_Entype,Dept_Id,Faculty_Id,Curiculum_Id,Std_Year_Enter,Std_Bank_Acc_No,YearStudy)
values('38014106','Chonlatorn','Chunhavikasit','10','107','01','07','2538','7302','3')



/* Student 4D */
Insert into Student(Std_Id,Std_Name_Eng,Std_Sname_Eng,Std_Entype,Dept_Id,Faculty_Id,Curiculum_Id,Std_Year_Enter,Std_Bank_Acc_No,YearStudy)
values('37014493','Siriroj','Rojwathanakul','10','107','01','07','2537','7001','4')

Insert into Student(Std_Id,Std_Name_Eng,Std_Sname_Eng,Std_Entype,Dept_Id,Faculty_Id,Curiculum_Id,Std_Year_Enter,Std_Bank_Acc_No,YearStudy)
values('37014588','Arada','Jearwiriyaboonya','10','107','01','07','2537','7002','4')


