/* Basic General Subject Group */
Insert into Subject(Subj_Id,Subj_Name_Eng,Subj_Type,Credit_Lec,Credit_Lab)
Values('03100002','Industrial Economics','05',2,0)

Insert into Subject(Subj_Id,Subj_Name_Eng,Subj_Type,Credit_Lec,Credit_Lab)
Values('03100003','Taxtion','05',2,0)

Insert into Subject(Subj_Id,Subj_Name_Eng,Subj_Type,Credit_Lec,Credit_Lab)
Values('03100005','Consumer Economics','05',2,0)

Insert into Subject(Subj_Id,Subj_Name_Eng,Subj_Type,Credit_Lec,Credit_Lab)
Values('03100021','Principle of Marketing','05',2,0)

Insert into Subject(Subj_Id,Subj_Name_Eng,Subj_Type,Credit_Lec,Credit_Lab)
Values('03100031','Business Administration','05',2,0)

Insert into Subject(Subj_Id,Subj_Name_Eng,Subj_Type,Credit_Lec,Credit_Lab)
Values('03100061','Introduction to the Studies of Laws','05',2,0)

Insert into Subject(Subj_Id,Subj_Name_Eng,Subj_Type,Credit_Lec,Credit_Lab)
Values('03100064','Labour Laws and Engineering Profession ACT.','05',2,0)

Insert into Subject(Subj_Id,Subj_Name_Eng,Subj_Type,Credit_Lec,Credit_Lab)
Values('03100075','Community Development','05',2,0)

Insert into Subject(Subj_Id,Subj_Name_Eng,Subj_Type,Credit_Lec,Credit_Lab)
Values('03100001','Introduction to Economics','05',2,0)

Insert into Subject(Subj_Id,Subj_Name_Eng,Subj_Type,Credit_Lec,Credit_Lab)
Values('03100004','Money and Banking','05',2,0)

Insert into Subject(Subj_Id,Subj_Name_Eng,Subj_Type,Credit_Lec,Credit_Lab)
Values('03100021','Principle of Marketing','05',2,0)

Insert into Subject(Subj_Id,Subj_Name_Eng,Subj_Type,Credit_Lec,Credit_Lab)
Values('03100031','Business Administration','05',2,0)

Insert into Subject(Subj_Id,Subj_Name_Eng,Subj_Type,Credit_Lec,Credit_Lab)
Values('03100066','Business and Commercial Laws','05',2,0)

Insert into Subject(Subj_Id,Subj_Name_Eng,Subj_Type,Credit_Lec,Credit_Lab)
Values('03100071','Introduction to Sociology','05',2,0)

Insert into Subject(Subj_Id,Subj_Name_Eng,Subj_Type,Credit_Lec,Credit_Lab)
Values('03100074','Socity and Economy','05',2,0)

Insert into Subject(Subj_Id,Subj_Name_Eng,Subj_Type,Credit_Lec,Credit_Lab)
Values('03150016','Industrial and Organization Psychology','03',2,0)

Insert into Subject(Subj_Id,Subj_Name_Eng,Subj_Type,Credit_Lec,Credit_Lab)
Values('03150030','Introduction to Physical Education','03',2,0)

Insert into Subject(Subj_Id,Subj_Name_Eng,Subj_Type,Credit_Lec,Credit_Lab)
Values('03150046','Engineering Information','03',2,0)

Insert into Subject(Subj_Id,Subj_Name_Eng,Subj_Type,Credit_Lec,Credit_Lab)
Values('03150062','Thai Civilization','03',2,0)

Insert into Subject(Subj_Id,Subj_Name_Eng,Subj_Type,Credit_Lec,Credit_Lab)
Values('03150067','Peace Study','03',2,0)

Insert into Subject(Subj_Id,Subj_Name_Eng,Subj_Type,Credit_Lec,Credit_Lab)
Values('03150076','Natural Resource Conservation','03',2,0)

Insert into Subject(Subj_Id,Subj_Name_Eng,Subj_Type,Credit_Lec,Credit_Lab)
Values('03150090','The Art of Thai Usage','03',2,0)




/* Curriculum for Bachelor of Engineering in Computer Engineering  */
Insert into Subject(Subj_Id,Subj_Name_Eng,Subj_Type,Credit_Lec,Credit_Lab)
Values('01072103','Data Structures and Algorithms','12',3,0)

Insert into Subject(Subj_Id,Subj_Name_Eng,Subj_Type,Credit_Lec,Credit_Lab)
Values('01072104','Switching Theory','12',3,0)

Insert into Subject(Subj_Id,Subj_Name_Eng,Subj_Type,Credit_Lec,Credit_Lab)
Values('01072106','Computer Organization and Architecture','12',3,0)

Insert into Subject(Subj_Id,Subj_Name_Eng,Subj_Type,Credit_Lec,Credit_Lab)
Values('01072107','Computer Laboratory I','12',0,2)

Insert into Subject(Subj_Id,Subj_Name_Eng,Subj_Type,Credit_Lec,Credit_Lab)
Values('01073105','Assembly and System Programming','12',3,0)

Insert into Subject(Subj_Id,Subj_Name_Eng,Subj_Type,Credit_Lec,Credit_Lab)
Values('01082102','System and Control Engineering','12',3,0)

Insert into Subject(Subj_Id,Subj_Name_Eng,Subj_Type,Credit_Lec,Credit_Lab)
Values('01073101','Computer Project I','12',0,2)

Insert into Subject(Subj_Id,Subj_Name_Eng,Subj_Type,Credit_Lec,Credit_Lab)
Values('01073103','Computer Laboratory II','12',0,2)

Insert into Subject(Subj_Id,Subj_Name_Eng,Subj_Type,Credit_Lec,Credit_Lab)
Values('01072105','Microprocessor Interfacing','12',3,0)

Insert into Subject(Subj_Id,Subj_Name_Eng,Subj_Type,Credit_Lec,Credit_Lab)
Values('01073106','Information System Analysis and Design','12',3,0)

Insert into Subject(Subj_Id,Subj_Name_Eng,Subj_Type,Credit_Lec,Credit_Lab)
Values('01073107','Communication Engineering','12',3,0)

Insert into Subject(Subj_Id,Subj_Name_Eng,Subj_Type,Credit_Lec,Credit_Lab)
Values('01070001','Mathematics for Computer Engineering','01',3,0)

Insert into Subject(Subj_Id,Subj_Name_Eng,Subj_Type,Credit_Lec,Credit_Lab)
Values('01073102','Computer Project II','12',0,2)

Insert into Subject(Subj_Id,Subj_Name_Eng,Subj_Type,Credit_Lec,Credit_Lab)
Values('01073104','Computer Laboratory III','12',0,2)

Insert into Subject(Subj_Id,Subj_Name_Eng,Subj_Type,Credit_Lec,Credit_Lab)
Values('01073108','Computer Network','12',3,0)

Insert into Subject(Subj_Id,Subj_Name_Eng,Subj_Type,Credit_Lec,Credit_Lab)
Values('01073109','Operating System I','12',3,0)

Insert into Subject(Subj_Id,Subj_Name_Eng,Subj_Type,Credit_Lec,Credit_Lab)
Values('01073110','Compiler Construction','12',3,0)

Insert into Subject(Subj_Id,Subj_Name_Eng,Subj_Type,Credit_Lec,Credit_Lab)
Values('01073111','Database System','12',3,0)

Insert into Subject(Subj_Id,Subj_Name_Eng,Subj_Type,Credit_Lec,Credit_Lab)
Values('01073112','Artificial Intelligence','12',3,0)

Insert into Subject(Subj_Id,Subj_Name_Eng,Subj_Type,Credit_Lec,Credit_Lab)
Values('01073100','Training Job','12',0,1)

Insert into Subject(Subj_Id,Subj_Name_Eng,Subj_Type,Credit_Lec,Credit_Lab)
Values('01074101','Project I','12',0,3)

Insert into Subject(Subj_Id,Subj_Name_Eng,Subj_Type,Credit_Lec,Credit_Lab)
Values('01074103','Expert System','13',3,0)

Insert into Subject(Subj_Id,Subj_Name_Eng,Subj_Type,Credit_Lec,Credit_Lab)
Values('01074111','Software Engineering','13',3,0)

Insert into Subject(Subj_Id,Subj_Name_Eng,Subj_Type,Credit_Lec,Credit_Lab)
Values('01074114','Management Information System','13',3,0)

Insert into Subject(Subj_Id,Subj_Name_Eng,Subj_Type,Credit_Lec,Credit_Lab)
Values('01074115','Office Automation','13',3,0)

Insert into Subject(Subj_Id,Subj_Name_Eng,Subj_Type,Credit_Lec,Credit_Lab)
Values('01074118','Robotic Engineering','13',3,0)

Insert into Subject(Subj_Id,Subj_Name_Eng,Subj_Type,Credit_Lec,Credit_Lab)
Values('01074124','Select Topics in Computer Communication','13',3,0)

Insert into Subject(Subj_Id,Subj_Name_Eng,Subj_Type,Credit_Lec,Credit_Lab)
Values('01074125','Select Topics in Information Technology(DBMS)','13',3,0)

Insert into Subject(Subj_Id,Subj_Name_Eng,Subj_Type,Credit_Lec,Credit_Lab)
Values('01074102','Project II','12',0,3)

Insert into Subject(Subj_Id,Subj_Name_Eng,Subj_Type,Credit_Lec,Credit_Lab)
Values('01074105','Pattern Recognition','13',3,0)

Insert into Subject(Subj_Id,Subj_Name_Eng,Subj_Type,Credit_Lec,Credit_Lab)
Values('01074113','Digital Signal Processing','13',3,0)

Insert into Subject(Subj_Id,Subj_Name_Eng,Subj_Type,Credit_Lec,Credit_Lab)
Values('01074116','Computer Crime and Counter Measurement','13',3,0)

Insert into Subject(Subj_Id,Subj_Name_Eng,Subj_Type,Credit_Lec,Credit_Lab)
Values('01074121','Operating System II','13',3,0)



/* Curriculum for Bachelor of Engineering in Computer Engineering (Continue) */
Insert into Subject(Subj_Id,Subj_Name_Eng,Subj_Type,Credit_Lec,Credit_Lab)
Values('01001004','Engineering Mathematics I','01',3,0)

Insert into Subject(Subj_Id,Subj_Name_Eng,Subj_Type,Credit_Lec,Credit_Lab)
Values('01010001','Electromagnetics','02',3,0)

Insert into Subject(Subj_Id,Subj_Name_Eng,Subj_Type,Credit_Lec,Credit_Lab)
Values('01191101','Electronic Engineering','12',3,0)

Insert into Subject(Subj_Id,Subj_Name_Eng,Subj_Type,Credit_Lec,Credit_Lab)
Values('01191102','Principles of Computer Programming','12',0,2)

Insert into Subject(Subj_Id,Subj_Name_Eng,Subj_Type,Credit_Lec,Credit_Lab)
Values('01191106','Computer Organization and Architecture','12',3,0)

Insert into Subject(Subj_Id,Subj_Name_Eng,Subj_Type,Credit_Lec,Credit_Lab)
Values('03010003','Technical English I','04',2,0)

Insert into Subject(Subj_Id,Subj_Name_Eng,Subj_Type,Credit_Lec,Credit_Lab)
Values('01001005','Engineering Mathematics II','01',3,0)

Insert into Subject(Subj_Id,Subj_Name_Eng,Subj_Type,Credit_Lec,Credit_Lab)
Values('01191103','Data Structure & Algorithms','12',3,0)

Insert into Subject(Subj_Id,Subj_Name_Eng,Subj_Type,Credit_Lec,Credit_Lab)
Values('01191104','Switching Theory','12',3,0)

Insert into Subject(Subj_Id,Subj_Name_Eng,Subj_Type,Credit_Lec,Credit_Lab)
Values('01191107','Computer Laboratory I','12',0,2)

Insert into Subject(Subj_Id,Subj_Name_Eng,Subj_Type,Credit_Lec,Credit_Lab)
Values('01192104','Assembly & System Programming','12',3,0)

Insert into Subject(Subj_Id,Subj_Name_Eng,Subj_Type,Credit_Lec,Credit_Lab)
Values('03010004','Technical English','04',2,0)

Insert into Subject(Subj_Id,Subj_Name_Eng,Subj_Type,Credit_Lec,Credit_Lab)
Values('01192101','Computer Project I','12',0,2)

Insert into Subject(Subj_Id,Subj_Name_Eng,Subj_Type,Credit_Lec,Credit_Lab)
Values('01191108','Computer Laboratory II','12',0,2)

Insert into Subject(Subj_Id,Subj_Name_Eng,Subj_Type,Credit_Lec,Credit_Lab)
Values('01191105','Microprocessor Interfacing','12',3,0)

Insert into Subject(Subj_Id,Subj_Name_Eng,Subj_Type,Credit_Lec,Credit_Lab)
Values('01192105','Information System Analysis and Design','12',3,0)

Insert into Subject(Subj_Id,Subj_Name_Eng,Subj_Type,Credit_Lec,Credit_Lab)
Values('01192110','Artificial Intelligence','12',3,0)

Insert into Subject(Subj_Id,Subj_Name_Eng,Subj_Type,Credit_Lec,Credit_Lab)
Values('03150046','Engineering Information','03',2,0)

Insert into Subject(Subj_Id,Subj_Name_Eng,Subj_Type,Credit_Lec,Credit_Lab)
Values('01192102','Computer Project II','12',0,2)

Insert into Subject(Subj_Id,Subj_Name_Eng,Subj_Type,Credit_Lec,Credit_Lab)
Values('01192103','Computer Laboratory III','12',0,2)

Insert into Subject(Subj_Id,Subj_Name_Eng,Subj_Type,Credit_Lec,Credit_Lab)
Values('01192106','Computer Network','12',3,0)

Insert into Subject(Subj_Id,Subj_Name_Eng,Subj_Type,Credit_Lec,Credit_Lab)
Values('01192107','Operating System I','12',3,0)

Insert into Subject(Subj_Id,Subj_Name_Eng,Subj_Type,Credit_Lec,Credit_Lab)
Values('01192108','Compiler Construction','12',3,0)

Insert into Subject(Subj_Id,Subj_Name_Eng,Subj_Type,Credit_Lec,Credit_Lab)
Values('01192109','Database System','12',3,0)

Insert into Subject(Subj_Id,Subj_Name_Eng,Subj_Type,Credit_Lec,Credit_Lab)
Values('01193101','Project I','12',0,3)

Insert into Subject(Subj_Id,Subj_Name_Eng,Subj_Type,Credit_Lec,Credit_Lab)
Values('03100002','Industrial Economics','05',2,0)

Insert into Subject(Subj_Id,Subj_Name_Eng,Subj_Type,Credit_Lec,Credit_Lab)
Values('01193103','Expert System','13',3,0)

Insert into Subject(Subj_Id,Subj_Name_Eng,Subj_Type,Credit_Lec,Credit_Lab)
Values('01193108','Computer Graphics','13',3,0)

Insert into Subject(Subj_Id,Subj_Name_Eng,Subj_Type,Credit_Lec,Credit_Lab)
Values('01193111','Software Engineering','13',3,0)

Insert into Subject(Subj_Id,Subj_Name_Eng,Subj_Type,Credit_Lec,Credit_Lab)
Values('01193114','Management Information System','13',3,0)

Insert into Subject(Subj_Id,Subj_Name_Eng,Subj_Type,Credit_Lec,Credit_Lab)
Values('01193118','Robotic Engineering','13',3,0)

Insert into Subject(Subj_Id,Subj_Name_Eng,Subj_Type,Credit_Lec,Credit_Lab)
Values('01193124','Select Topic in Information Technology(DBMS)','13',3,0)

Insert into Subject(Subj_Id,Subj_Name_Eng,Subj_Type,Credit_Lec,Credit_Lab)
Values('01193128','Select Topic in Hardware Technology','13',3,0)

Insert into Subject(Subj_Id,Subj_Name_Eng,Subj_Type,Credit_Lec,Credit_Lab)
Values('01193102','Project II','12',0,3)

Insert into Subject(Subj_Id,Subj_Name_Eng,Subj_Type,Credit_Lec,Credit_Lab)
Values('03100032','Industrial Management','05',2,0)

Insert into Subject(Subj_Id,Subj_Name_Eng,Subj_Type,Credit_Lec,Credit_Lab)
Values('01193105','Pattern Recognition','13',3,0)

Insert into Subject(Subj_Id,Subj_Name_Eng,Subj_Type,Credit_Lec,Credit_Lab)
Values('01193113','Digital Signal Processing','13',3,0)

Insert into Subject(Subj_Id,Subj_Name_Eng,Subj_Type,Credit_Lec,Credit_Lab)
Values('01193122','Computer Language Concepts','13',3,0) 

