/* Subject for Curriculum for Bachelor of Engineering in Computer Engineering */
Insert into Subject_For_Register(Subj_Id,Curiculum_Id,Faculty_Id,Term,YearStudy)
Values('01072103','07','01','2','2')

Insert into Subject_For_Register(Subj_Id,Curiculum_Id,Faculty_Id,Term,YearStudy)
Values('01072104','07','01','2','2')

Insert into Subject_For_Register(Subj_Id,Curiculum_Id,Faculty_Id,Term,YearStudy)
Values('01072106','07','01','2','2')

Insert into Subject_For_Register(Subj_Id,Curiculum_Id,Faculty_Id,Term,YearStudy)
Values('01072107','07','01','2','2')

Insert into Subject_For_Register(Subj_Id,Curiculum_Id,Faculty_Id,Term,YearStudy)
Values('01073105','07','01','2','2')

Insert into Subject_For_Register(Subj_Id,Curiculum_Id,Faculty_Id,Term,YearStudy)
Values('01082102','07','01','2','2')



Insert into Subject_For_Register(Subj_Id,Curiculum_Id,Faculty_Id,Term,YearStudy)
Values('01073101','07','01','1','3')

Insert into Subject_For_Register(Subj_Id,Curiculum_Id,Faculty_Id,Term,YearStudy)
Values('01073103','07','01','1','3')

Insert into Subject_For_Register(Subj_Id,Curiculum_Id,Faculty_Id,Term,YearStudy)
Values('01072105','07','01','1','3')

Insert into Subject_For_Register(Subj_Id,Curiculum_Id,Faculty_Id,Term,YearStudy)
Values('01073106','07','01','1','3')

Insert into Subject_For_Register(Subj_Id,Curiculum_Id,Faculty_Id,Term,YearStudy)
Values('01073107','07','01','1','3')

Insert into Subject_For_Register(Subj_Id,Curiculum_Id,Faculty_Id,Term,YearStudy)
Values('01070001','07','01','1','3')



Insert into Subject_For_Register(Subj_Id,Curiculum_Id,Faculty_Id,Term,YearStudy)
Values('03150016','07','01','1','3')

Insert into Subject_For_Register(Subj_Id,Curiculum_Id,Faculty_Id,Term,YearStudy)
Values('03150030','07','01','1','3')

Insert into Subject_For_Register(Subj_Id,Curiculum_Id,Faculty_Id,Term,YearStudy)
Values('03150046','07','01','1','3')

Insert into Subject_For_Register(Subj_Id,Curiculum_Id,Faculty_Id,Term,YearStudy)
Values('03150062','07','01','1','3')

Insert into Subject_For_Register(Subj_Id,Curiculum_Id,Faculty_Id,Term,YearStudy)
Values('03150067','07','01','1','3')

Insert into Subject_For_Register(Subj_Id,Curiculum_Id,Faculty_Id,Term,YearStudy)
Values('03150076','07','01','1','3')

Insert into Subject_For_Register(Subj_Id,Curiculum_Id,Faculty_Id,Term,YearStudy)
Values('03150090','07','01','1','3')



Insert into Subject_For_Register(Subj_Id,Curiculum_Id,Faculty_Id,Term,YearStudy)
Values('01073102','07','01','2','3')

Insert into Subject_For_Register(Subj_Id,Curiculum_Id,Faculty_Id,Term,YearStudy)
Values('01073104','07','01','2','3')

Insert into Subject_For_Register(Subj_Id,Curiculum_Id,Faculty_Id,Term,YearStudy)
Values('01073108','07','01','2','3')

Insert into Subject_For_Register(Subj_Id,Curiculum_Id,Faculty_Id,Term,YearStudy)
Values('01073109','07','01','2','3')

Insert into Subject_For_Register(Subj_Id,Curiculum_Id,Faculty_Id,Term,YearStudy)
Values('01073110','07','01','2','3')

Insert into Subject_For_Register(Subj_Id,Curiculum_Id,Faculty_Id,Term,YearStudy)
Values('01073111','07','01','2','3')

Insert into Subject_For_Register(Subj_Id,Curiculum_Id,Faculty_Id,Term,YearStudy)
Values('01073112','07','01','2','3')



Insert into Subject_For_Register(Subj_Id,Curiculum_Id,Faculty_Id,Term,YearStudy)
Values('01074101','07','01','1','4')

Insert into Subject_For_Register(Subj_Id,Curiculum_Id,Faculty_Id,Term,YearStudy)
Values('01074103','07','01','1','4')

Insert into Subject_For_Register(Subj_Id,Curiculum_Id,Faculty_Id,Term,YearStudy)
Values('01074111','07','01','1','4')

Insert into Subject_For_Register(Subj_Id,Curiculum_Id,Faculty_Id,Term,YearStudy)
Values('01074114','07','01','1','4')

Insert into Subject_For_Register(Subj_Id,Curiculum_Id,Faculty_Id,Term,YearStudy)
Values('01074115','07','01','1','4')

Insert into Subject_For_Register(Subj_Id,Curiculum_Id,Faculty_Id,Term,YearStudy)
Values('01074118','07','01','1','4')

Insert into Subject_For_Register(Subj_Id,Curiculum_Id,Faculty_Id,Term,YearStudy)
Values('01074124','07','01','1','4')

Insert into Subject_For_Register(Subj_Id,Curiculum_Id,Faculty_Id,Term,YearStudy)
Values('01074126','07','01','1','4')



Insert into Subject_For_Register(Subj_Id,Curiculum_Id,Faculty_Id,Term,YearStudy)
Values('03100001','07','01','1','4')

Insert into Subject_For_Register(Subj_Id,Curiculum_Id,Faculty_Id,Term,YearStudy)
Values('03100004','07','01','1','4')

Insert into Subject_For_Register(Subj_Id,Curiculum_Id,Faculty_Id,Term,YearStudy)
Values('03100021','07','01','1','4')

Insert into Subject_For_Register(Subj_Id,Curiculum_Id,Faculty_Id,Term,YearStudy)
Values('03100032','07','01','1','4')

Insert into Subject_For_Register(Subj_Id,Curiculum_Id,Faculty_Id,Term,YearStudy)
Values('03100031','07','01','1','4')

Insert into Subject_For_Register(Subj_Id,Curiculum_Id,Faculty_Id,Term,YearStudy)
Values('03100061','07','01','1','4')

Insert into Subject_For_Register(Subj_Id,Curiculum_Id,Faculty_Id,Term,YearStudy)
Values('03100071','07','01','1','4')

Insert into Subject_For_Register(Subj_Id,Curiculum_Id,Faculty_Id,Term,YearStudy)
Values('03100074','07','01','1','4')


Insert into Subject_For_Register(Subj_Id,Curiculum_Id,Faculty_Id,Term,YearStudy)
Values('01074102','07','01','2','4')

Insert into Subject_For_Register(Subj_Id,Curiculum_Id,Faculty_Id,Term,YearStudy)
Values('01074105','07','01','2','4')

Insert into Subject_For_Register(Subj_Id,Curiculum_Id,Faculty_Id,Term,YearStudy)
Values('01074113','07','01','2','4')

Insert into Subject_For_Register(Subj_Id,Curiculum_Id,Faculty_Id,Term,YearStudy)
Values('01074116','07','01','2','4')

Insert into Subject_For_Register(Subj_Id,Curiculum_Id,Faculty_Id,Term,YearStudy)
Values('01074121','07','01','2','4')


Insert into Subject_For_Register(Subj_Id,Curiculum_Id,Faculty_Id,Term,YearStudy)
Values('03100002','07','01','2','4')

Insert into Subject_For_Register(Subj_Id,Curiculum_Id,Faculty_Id,Term,YearStudy)
Values('03100003','07','01','2','4')

Insert into Subject_For_Register(Subj_Id,Curiculum_Id,Faculty_Id,Term,YearStudy)
Values('03100005','07','01','2','4')

Insert into Subject_For_Register(Subj_Id,Curiculum_Id,Faculty_Id,Term,YearStudy)
Values('03100021','07','01','2','4')

Insert into Subject_For_Register(Subj_Id,Curiculum_Id,Faculty_Id,Term,YearStudy)
Values('03100031','07','01','2','4')

Insert into Subject_For_Register(Subj_Id,Curiculum_Id,Faculty_Id,Term,YearStudy)
Values('03100064','07','01','2','4')

Insert into Subject_For_Register(Subj_Id,Curiculum_Id,Faculty_Id,Term,YearStudy)
Values('03100075','07','01','2','4')


Insert into Subject_For_Register(Subj_Id,Curiculum_Id,Faculty_Id,Term,YearStudy)
Values('03100001','07','01','2','4')

Insert into Subject_For_Register(Subj_Id,Curiculum_Id,Faculty_Id,Term,YearStudy)
Values('03100004','07','01','2','4')

Insert into Subject_For_Register(Subj_Id,Curiculum_Id,Faculty_Id,Term,YearStudy)
Values('03100021','07','01','2','4')

Insert into Subject_For_Register(Subj_Id,Curiculum_Id,Faculty_Id,Term,YearStudy)
Values('03100031','07','01','2','4')

Insert into Subject_For_Register(Subj_Id,Curiculum_Id,Faculty_Id,Term,YearStudy)
Values('03100066','07','01','2','4')

Insert into Subject_For_Register(Subj_Id,Curiculum_Id,Faculty_Id,Term,YearStudy)
Values('03100071','07','01','2','4')

Insert into Subject_For_Register(Subj_Id,Curiculum_Id,Faculty_Id,Term,YearStudy)
Values('03100074','07','01','2','4')






/* Subject for Curriculum for Bachelor of Engineering in Computer Engineering (Continue) */
Insert into Subject_For_Register(Subj_Id,Curiculum_Id,Faculty_Id,Term,YearStudy)
Values('01001004','19','01','1','1')

Insert into Subject_For_Register(Subj_Id,Curiculum_Id,Faculty_Id,Term,YearStudy)
Values('01010001','19','01','1','1')

Insert into Subject_For_Register(Subj_Id,Curiculum_Id,Faculty_Id,Term,YearStudy)
Values('01191101','19','01','1','1')

Insert into Subject_For_Register(Subj_Id,Curiculum_Id,Faculty_Id,Term,YearStudy)
Values('01191102','19','01','1','1')

Insert into Subject_For_Register(Subj_Id,Curiculum_Id,Faculty_Id,Term,YearStudy)
Values('01191106','19','01','1','1')

Insert into Subject_For_Register(Subj_Id,Curiculum_Id,Faculty_Id,Term,YearStudy)
Values('03010003','19','01','1','1')








Insert into Subject_For_Register(Subj_Id,Curiculum_Id,Faculty_Id,Term,YearStudy)
Values('01001005','19','01','2','1')

Insert into Subject_For_Register(Subj_Id,Curiculum_Id,Faculty_Id,Term,YearStudy)
Values('01191103','19','01','2','1')

Insert into Subject_For_Register(Subj_Id,Curiculum_Id,Faculty_Id,Term,YearStudy)
Values('01191104','19','01','2','1')

Insert into Subject_For_Register(Subj_Id,Curiculum_Id,Faculty_Id,Term,YearStudy)
Values('01191107','19','01','2','1')

Insert into Subject_For_Register(Subj_Id,Curiculum_Id,Faculty_Id,Term,YearStudy)
Values('01192104','19','01','2','1')

Insert into Subject_For_Register(Subj_Id,Curiculum_Id,Faculty_Id,Term,YearStudy)
Values('03010004','19','01','2','1')







Insert into Subject_For_Register(Subj_Id,Curiculum_Id,Faculty_Id,Term,YearStudy)
Values('01192101','19','01','1','2')

Insert into Subject_For_Register(Subj_Id,Curiculum_Id,Faculty_Id,Term,YearStudy)
Values('01191108','19','01','1','2')

Insert into Subject_For_Register(Subj_Id,Curiculum_Id,Faculty_Id,Term,YearStudy)
Values('01191105','19','01','1','2')

Insert into Subject_For_Register(Subj_Id,Curiculum_Id,Faculty_Id,Term,YearStudy)
Values('01192105','19','01','1','2')

Insert into Subject_For_Register(Subj_Id,Curiculum_Id,Faculty_Id,Term,YearStudy)
Values('01192110','19','01','1','2')

Insert into Subject_For_Register(Subj_Id,Curiculum_Id,Faculty_Id,Term,YearStudy)
Values('03150046','19','01','1','2')






Insert into Subject_For_Register(Subj_Id,Curiculum_Id,Faculty_Id,Term,YearStudy)
Values('01192102','19','01','2','2')

Insert into Subject_For_Register(Subj_Id,Curiculum_Id,Faculty_Id,Term,YearStudy)
Values('01192103','19','01','2','2')

Insert into Subject_For_Register(Subj_Id,Curiculum_Id,Faculty_Id,Term,YearStudy)
Values('01192106','19','01','2','2')

Insert into Subject_For_Register(Subj_Id,Curiculum_Id,Faculty_Id,Term,YearStudy)
Values('01192107','19','01','2','2')

Insert into Subject_For_Register(Subj_Id,Curiculum_Id,Faculty_Id,Term,YearStudy)
Values('01192108','19','01','2','2')

Insert into Subject_For_Register(Subj_Id,Curiculum_Id,Faculty_Id,Term,YearStudy)
Values('01192109','19','01','2','2')








Insert into Subject_For_Register(Subj_Id,Curiculum_Id,Faculty_Id,Term,YearStudy)
Values('01193101','19','01','1','3')

Insert into Subject_For_Register(Subj_Id,Curiculum_Id,Faculty_Id,Term,YearStudy)
Values('03100002','19','01','1','3')

Insert into Subject_For_Register(Subj_Id,Curiculum_Id,Faculty_Id,Term,YearStudy)
Values('01193103','19','01','1','3')

Insert into Subject_For_Register(Subj_Id,Curiculum_Id,Faculty_Id,Term,YearStudy)
Values('01193108','19','01','1','3')

Insert into Subject_For_Register(Subj_Id,Curiculum_Id,Faculty_Id,Term,YearStudy)
Values('01193111','19','01','1','3')

Insert into Subject_For_Register(Subj_Id,Curiculum_Id,Faculty_Id,Term,YearStudy)
Values('01193114','19','01','1','3')

Insert into Subject_For_Register(Subj_Id,Curiculum_Id,Faculty_Id,Term,YearStudy)
Values('01193118','19','01','1','3')

Insert into Subject_For_Register(Subj_Id,Curiculum_Id,Faculty_Id,Term,YearStudy)
Values('01193124','19','01','1','3')

Insert into Subject_For_Register(Subj_Id,Curiculum_Id,Faculty_Id,Term,YearStudy)
Values('01193126','19','01','1','3')






Insert into Subject_For_Register(Subj_Id,Curiculum_Id,Faculty_Id,Term,YearStudy)
Values('01193102','19','01','2','3')

Insert into Subject_For_Register(Subj_Id,Curiculum_Id,Faculty_Id,Term,YearStudy)
Values('03100032','19','01','2','3')

Insert into Subject_For_Register(Subj_Id,Curiculum_Id,Faculty_Id,Term,YearStudy)
Values('01193105','19','01','2','3')

Insert into Subject_For_Register(Subj_Id,Curiculum_Id,Faculty_Id,Term,YearStudy)
Values('01193113','19','01','2','3')

Insert into Subject_For_Register(Subj_Id,Curiculum_Id,Faculty_Id,Term,YearStudy)
Values('01193122','19','01','2','3')

